CREATE TABLE IF NOT EXISTS user (
  id   INT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(128) UNIQUE NOT NULL,
  password VARCHAR(128) NOT NULL ,
  deleted INT DEFAULT 0
)
  ENGINE = InnoDB
  DEFAULT CHARSET = utf8mb4
